### ISSUE TITLE
[Feature request: RISC-V] Enable `TUKLIB_FAST_UNALIGNED_ACCESS` flag for RISC-V?

### ISSUE THREAD

**Issue by guoyuqi020** [tukaani-project/xz#146]
I noticed that the `TUKLIB_FAST_UNALIGNED_ACCESS` flag is always disabled for RISC-V, even though RISC-V supports unaligned access.

Perhaps consider enabling it?

**Comment by Larhzu** [comment]
Assuming no bugs, autodetection was enabled a year ago and is included in 5.6.x. See the commits 2f81ac852bc5aafc91c8e2adc66b5114761703c4 and 9a78971261bc67622cbd7dae02f6966968ac1393. They check if the preprocessor defines __riscv_misaligned_fast. That macro exists because only some RISC-V processors have fast misaligned/unaligned access. See:

https://github.com/riscv-non-isa/riscv-c-api-doc/blob/main/src/c-api.adoc

GCC and Clang should define the macro based on the target processor. See the -mcpu, -march, and -mtune flags.

$ riscv64-linux-gnu-cpp -mtune=sifive-7-series -dM /dev/null | grep align
#define __riscv_misaligned_slow 1

$ riscv64-linux-gnu-cpp -mtune=size -dM /dev/null | grep align
#define __riscv_misaligned_fast 1

You can still override the autodetection in xz with `configure --enable-unaligned-access` or `cmake -DTUKLIB_FAST_UNALIGNED_ACCESS=ON`.

**Comment by guoyuqi020** [comment]
Thanks for your information, I get it.

Just a second check. I'm using 5.4.7 (old stable). Although 5.4.7 was released after these two commits were pushed, it seems that it still did not include the revisions you mentioned.

So, only 5.6.x supports such features?

**Comment by Larhzu** [comment]
That's correct, the autodetection wasn't backported to 5.4.7 or 5.2.13. I have tried to keep each stable branch largely as "bug fixes only" to reduce risk of regressions (and regressions have still occurred a few times).

I haven't tested the code on RISC-V and haven't heard reports from others either. The autodetection change was done based on the documentation I found. Thus it felt better to add such a change in alpha/beta versions first and then only in a new stable branch.

You can still enable unaligned access manually at build time with 5.4.7 and older versions.

If you wish to improve RISC-V support, look at src/liblzma/common/memcmplen.h. The long #if at the beginning of lzma_memcmplen() covers x86-64 and ARM64 at the moment but likely it's fine on little endian RV64 too when unaligned access has been enabled. Adding RV64 detection to that long #if line should improve *encoder* speed slightly (like one or two percent, so not much but by a measurable amount).

**Comment by guoyuqi020** [comment]
Thanks for your help. Since my question has been resolved, please let me close this issue.
