### ISSUE TITLE
How does 5.2.4 fix CVE-2024-47611? We cannot upgrade to 5.6.3 for the time being.

### ISSUE THREAD

**Issue by Adolph-WSY** [tukaani-project/xz#147]
Thank you very much for fixing CVE-2024-47611: Argument injection on Windows in time. 
However, some of our products that cannot be upgraded are still using version 5.2.4 that has not switched the CMakefile build, which makes it impossible to apply the corresponding commit of the 5.2 branch for repair. 

How should this vulnerability be fixed for versions 5.2.4 and earlier?

**Comment by Larhzu** [comment]
First, are you using the command line tools (*.exe files like xz.exe) on Windows? The issue affects only those. If you only use liblzma, this issue is not relevant.

Even if you do use the command line tools, if you never pass untrusted filenames to them (for example, you only use the tools in a pipe) then the vulnerability isn't relevant.

Anyway, for 5.2.4, you can apply the commit 9ecccb3d5f67205f156f8c7ad1ec98436c165abd without the CMakeLists.txt part. 5.2.4 doesn't have CMake support. The changes to CMakeLists.txt were needed only for MSVC. Building the command line tools with MSVC isn't supported in 5.2.4.

The command line tools in 5.2.4 can be built for Windows only using MinGW or MinGW-w64 with help from MSYS or MSYS2 to run ./configure && make (possibly via windows/build.bash). The modifications to common_w32res.rc and the addition of w32_application.manifest are enough to apply the fix in this case. You don't even need the Makefile.am change, in fact, you might wish to omit that if building from a tarball and applying a patch because this way you avoid unneeded regeneration of the build system files.

**Comment by Larhzu** [comment]
@Adolph-WSY: Was the problem solved or is more information needed?

**Comment by Larhzu** [comment]
Omit the Makefile.am change from the commit. When Makefile.am is changed (file timestamp is updated), the build system attempts to run automake-1.16 to update the corresponding Makefile.in. You could Automake it but it's waste of time if this is the only reason you would need it.

The Makefile.am change is there mostly so that the new files get included in a newly-created distribution tarball. Changing Makefile.am isn't needed to make the fix work.

It's the lines at the end of common_w32res.rc that do the actual work of including the manifest file in the executables.

**Comment by Larhzu** [comment]
@Adolph-WSY: Has this been solved? Did you manage to modify `common_w32res.rc` and add the new file `w32_application.manifest` and have a working build?

**Comment by Larhzu** [comment]
There is more information about the vulnerability at <https://worst.fit/>.
