### ISSUE TITLE
[Feature Request]: SeekableXZInputStream ability to write straight into java.nio.ByteBuffer

### ISSUE THREAD

**Issue by xbotuk** [tukaani-project/xz#19]
### Describe the Feature

Can you please add methods in SeekableXZInputStream ability to write straight into an existing java.nio.ByteBuffer

This is to replicate something like 

```
ByteBuffer bytebuffer = ByteBuffer.allocateDirect(65536);
RandomAccessFile raf = new RandomAccessFile(filePath, "r");
FileChannel fc = raf.getChannel();
ByteBuffer.allocateDirect(this.bufferSize);

// call next statements many ties  by seeking various positions
fc.read(bytebuffer);
bytebuffer.flip();
```

### Expected Complications

ByteBuffer is available since old versions of java, so adding this feature should not be an issue.

### Will I try to implement this new feature?

No

**Comment by JiaT75** [comment]
Hi! Thank you for the feature request. Unfortunately, this is the wrong repository for this since this is XZ Utils (the C version). XZ for Java has not been moved to GitHub yet, so the code repository is still located at https://git.tukaani.org/xz-java.git.

So, until we move XZ for Java to GitHub, you will need to request features or report bugs either to xz@tukaani.org or the xz-devel mailing list. Instructions for subscribing to the mailing list are documented here: https://tukaani.org/xz/lists.html. You do not need to subscribe to the mailing list to email xz@tukaani.org, but then only the maintainers will be able to see your mails.

Thanks again for the feature request!
